/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthorsUsernameIndexRouteImport } from './routes/authors.$username.index'
import { Route as AuthorsUsernamePostRouteImport } from './routes/authors.$username.$post'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsUsernameIndexRoute = AuthorsUsernameIndexRouteImport.update({
  id: '/authors/$username/',
  path: '/authors/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsUsernamePostRoute = AuthorsUsernamePostRouteImport.update({
  id: '/authors/$username/$post',
  path: '/authors/$username/$post',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors/$username/$post': typeof AuthorsUsernamePostRoute
  '/authors/$username/': typeof AuthorsUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors/$username/$post': typeof AuthorsUsernamePostRoute
  '/authors/$username': typeof AuthorsUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors/$username/$post': typeof AuthorsUsernamePostRoute
  '/authors/$username/': typeof AuthorsUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/authors/$username/$post' | '/authors/$username/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/authors/$username/$post' | '/authors/$username'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/authors/$username/$post'
    | '/authors/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthorsUsernamePostRoute: typeof AuthorsUsernamePostRoute
  AuthorsUsernameIndexRoute: typeof AuthorsUsernameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$username/': {
      id: '/authors/$username/'
      path: '/authors/$username'
      fullPath: '/authors/$username/'
      preLoaderRoute: typeof AuthorsUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$username/$post': {
      id: '/authors/$username/$post'
      path: '/authors/$username/$post'
      fullPath: '/authors/$username/$post'
      preLoaderRoute: typeof AuthorsUsernamePostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthorsUsernamePostRoute: AuthorsUsernamePostRoute,
  AuthorsUsernameIndexRoute: AuthorsUsernameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
